### PR TITLE
automatically loads timeline on widget id change

### PR DESCRIPTION
**Pull request by e111077**
Added feature: Loads the timeline automatically when the `dataWidgetId` is changed. Uses a promise structure to achieve this.

### CODE REVIEW

**Comment by LasaleFamine** [comment]
Hi @e111077 and thanks for this PR.
Actually, testing your change, I'm facing a problem: with a single `<twitter-timeline>` tag, two `iframe`s of the widget are loaded.
Are you not facing the same issue testing it with the `demo.html` component?

**Comment by e111077** [comment]
Hmm; I was testing it in my own application. Thanks for the heads up; I'll take a look

**Comment by e111077** [comment]
It seems as if this is a general issue related to calling `loadTimeline()` quickly in succession. Creating the timeline is asynchronous, so if `loadTimeline()` is synchronously called twice then calling `removeTimeline` (also synchronous) before any timelines have been created results in a noOp

**Comment by LasaleFamine** [comment]
I've just got that `this.loadTimeline()` is called two times: one in `_onTwttLoad` listener and another time inside the `_dataWidgetIdChanged` observer.
Removing the one within the listener seems to solve the problem.

What do you think?

**Comment by e111077** [comment]
That would be the cleanest way to fix this immediate issue, but this exposes a larger underlying issue of trying to remove not-yet-existent timelines by calling `loadTimeline` too quickly in succession. This can also happen if the databinding to `dataWidgetId` programmatically changes quickly.

**Comment by e111077** [comment]
Proposed a change; let me know if you think it is too complex

**Comment by LasaleFamine** [comment]
Hi @e111077 it's nice for me! I tested it and works as expected.

Are you able to solve the conflict about the merge so I can automatically merge the PR?

Thank you so much for your contribution!

**Comment by e111077** [comment]
rebased and refactored

**Comment by LasaleFamine** [comment]
Bumped to v0.1.0.

Thanks again @e111077!

**Pull request merged**
